version: '3'
services:
  nginx-php:
    image: trafex/php-nginx:latest # Remplacez par le nom de votre image Docker personnalisée
    container_name: nginx-php-container
    ports:
      - "80:80"
    volumes:
      - ./php-code:/var/www/html
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf
      - ./php-config/php.ini:/usr/local/etc/php/conf.d/php.ini
